### PR TITLE
changes ... #crysx

### PR DESCRIPTION
**Pull request by chrysophylax69**
attributes - makefile.unix - removed secp256k1 - other small changes ... #crysx

### CODE REVIEW

**Comment by chrysophylax69** [comment]
devs - please hold back on this pull request ... i have found an issue with the setup and trying to get it fixed ... seeking the help of another experienced dev currently ...

please do NOT merge yet ... #crysx

**Comment by joshafest** [comment]
do not worry . 
we will fix it ourself when have time , do not waste your time in that ....just releax.

**Comment by chrysophylax69** [comment]
tanx josh ...

but all good now ... it wasnt the code - it was the pol stratum settings ...

running VERY well now ... tested lodiff and now hidiff ...

coin code is stable - though the only isue was the location of the seednodes ... the daemon didnt do the search for them - so even though they are hardcoded - the daemon ignores them ...

but a merge is fine if you need to - though the other makefiles need redoing also ...

#crysx

**Comment by limxdev** [comment]
Hmm... I have merge it. I can make later a rollback. ...If it not works.

Chris

**Pull request merged**
